### ISSUE TITLE
Notes doesn't save or delete (modify) when keyboard is active on mobiles. Also add trash button in Notes modal. 

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#100]
I found this strange thing. The notes doesn't save or get modified when the keyboard is active (on mobile). It is very tricky to shut the keyboard in order to save it. And same issue while deleting a note.

Also, add a trash button or delete note button on Notes modal.

**Comment by marwan** [comment]
this should be done as per https://github.com/marwan/quranwbw-v4/commit/5c1420c2147b19a68f5aa86537af5c11427afa62.

can reopen if issue persist.
