### ISSUE TITLE
When you change mode from Mushaf page to normal mode. There should be load previous verses and should display all remaining verses.

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#116]

**Comment by marwan** [comment]
load previous verses is not yet implemented, and load all remaining verses should work normally

**Comment by Ayman24x7** [comment]
Yeah. Just that load previous verses shall fix this. Also, it's important for before launch. (this feature was in v3)

**Comment by Ayman24x7** [comment]
This is actually completed.
