### ISSUE TITLE
Translation modal in Mushaf mode (just like tafsir)

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#122]

**Comment by marwan** [comment]
this is done https://github.com/marwan/quranwbw-v4/commit/2aa19f4916cd38c538e2b6cecbbf0da2bb915567.

**Comment by marwan** [comment]
done as per https://github.com/marwan/quranwbw-v4/commit/4f2fab0429e7b953013b056c423c70b7ea0a2b59.
