### ISSUE TITLE
Cleanup duplicate links on Homepage Dropdown 

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#133]
![image](https://github.com/marwan/quranwbw-v4/assets/86475124/df510085-06f4-4644-9a4e-2886a0442c94)

**Comment by marwan** [comment]
this is done as per https://github.com/marwan/quranwbw-v4/commit/4038f86555e83f1ecbfd4a343bdec2d7b8c1f846.

![image](https://github.com/user-attachments/assets/bd52d68b-266d-4b73-811f-3ad0a1602f08)
