### ISSUE TITLE
Make Dropdown options in settings not to text wrap, so each option comes in single line, able to read it properly. (There is sufficient screen space for this)

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#146]

**Comment by Ayman24x7** [comment]
![Screenshot_20240702_225850_Brave](https://github.com/marwan/quranwbw-v4/assets/86475124/50f9a3ad-55b9-4bdd-a2b5-59794bdb10e1)

**Comment by marwan** [comment]
This was done as per https://github.com/marwan/quranwbw-v4/commit/02efb66532a38664e7d72538cc90347824aecf8d.
