### ISSUE TITLE
Duas in navigation results and duas list in navigation panel 

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#157]
In duas page

When we open navigation panel. 

It should display the duas list instead of Surahs list.

Also, if I type

18:10 and that Ayah is also a Dua, then it should display under search results a new (Go to Dua - 18:10) and navigates to that dua instead.

**Comment by marwan** [comment]
Added duas list in duas page in https://github.com/marwan/quranwbw-v4/commit/ef652a59e496688882caa66c4f07844f1f90ec61.

I think this should work for now, the other thing can be kept for future.

**Comment by Ayman24x7** [comment]
Okay should I make a new issue for that (Dua Ayahs in search results)?
