### ISSUE TITLE
Option /toggle to hide name of translation and transliteration under each Ayah in settings to increase user experience.

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#164]
Option/toggle to hide name of translation and transliteration under each Ayah in settings to increase user experience. 

Also, disable/gray this option when more than 1 translations and/or more than 1 transliteration are selected in order to differentiate between the multiples.

However, if only one translation and one transliteration is selected, then keep it enabled.

**Comment by marwan** [comment]
then I guess we can move back to hiding the author name if only 1 is selected? then there's no need to add any additional toggle in settings

**Comment by Ayman24x7** [comment]
Okay, but maybe we can see if there will be a follow up request to see the name of the author in future. For now we can hide it.
