### ISSUE TITLE
V4 Tajweed fonts final update (pages 78, 203, 250 and 266)

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#179]
Got final testing results from Quran.com team. Their Production release is very close. 

These 4 pages needed to be fixed. Hence, updated. Kindly upload these updated fonts.

**Comment by marwan** [comment]
uploaded the new fonts at CDN.

![image](https://github.com/user-attachments/assets/7d029d4b-fcfa-4328-b22b-76f468cd6e28)
