### ISSUE TITLE
add credits for Tajweed fonts

### ISSUE THREAD

**Issue by marwan** [marwan/quranwbw-v4#20]
Tajweed fonts were created using Easy Quran - Dar Al Marifa Tajweed Mushaf and King Fahad Glorious Quran Printing Complex (KFGQPC) - Uthmanic Hafs V4 Fonts after receiving permission from both by our brothers at Quran.com.

**Comment by Ayman24x7** [comment]
This should be a note (ℹ️) when you activate Tajweed colors.

If you want to add Credits (all the people who worked for the project - then it is hidden inside every Tajweed font file.) I'll send it to you later.
