### ISSUE TITLE
Add another Urdu Translation

### ISSUE THREAD

**Issue by shariquealavi** [marwan/quranwbw-v4#37]
[TranslationData.zip](https://github.com/marwan/quranwbw-svelte/files/14860811/TranslationData.zip)

I suggest adding this translation data to your website as well. It is ayat by ayat Urdu translation by Dr Israr Ahmed from Quran.com

**Comment by marwan** [comment]
JazakAllah brother, I will look into this 👍

**Comment by marwan** [comment]
this was done as per https://github.com/marwan/quranwbw-v4/commit/b3010578b1745c12c301016bdd3aa2697ec018b0.
