### ISSUE TITLE
New Options menu [...] on Continuous/Mushaf layouts

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#53]
When you tap on a word in continuous mode, at the top it will show tool-tip translation/transliteration, we can add a (...) three dots option menu above the tool-tip which will display options menu. If tool-tip is turned off then it will only show the (...) three dots. Under this menu, we can provide bookmark, advance Play, morphology, go to page, notes and share verse functions. Or we can provide tap-and-hold to close tool-tip and show 3 dots. End of ayah should also show same.

![image](https://github.com/marwan/quranwbw-v4/assets/86475124/d35fc5cc-89db-4e55-8517-a8bf75c9d0a5)

**Comment by marwan** [comment]
@Ayman24x7 this is already done right?

**Comment by Ayman24x7** [comment]
Yeah, we added it under the Ayah icons instead. And also this suggestion felt uneasy/messy. I'll close it.
