### ISSUE TITLE
Supplications, Mushaf pages, and Morphology (header) navigation dropdown is missing (needs to be added) 

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#68]
Supplications should have only supplications listed.

Morphology page should have key search input as minimum.

Mushaf pages should have surah as list (no need verse here), however, page, juz and default (key) in search input.

**Comment by marwan** [comment]
@Ayman24x7 this is done right?

**Comment by Ayman24x7** [comment]
Yes it's done.
