### ISSUE TITLE
Often finding data loading errors on Mushaf pages and sometimes on website. Needs to be investigated. 

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#82]
![Screenshot_20240526_043455_Brave](https://github.com/marwan/quranwbw-v4/assets/86475124/77946db8-77c3-41b2-9757-2bb493851806)

**Comment by marwan** [comment]
@Ayman24x7 this should be fixed now. There was an error with some configuration on our API. I've been checking the logs now and Alhamdulillah no more errors.
