### ISSUE TITLE
Mushaf mode top line cropping issues (line height or top negative margin)

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#92]

**Comment by marwan** [comment]
@Ayman24x7 can you please provide an example page please

**Comment by Ayman24x7** [comment]
Page 11 (many pages but this is an example.) 

![Uploading Screenshot_20240606_043527_Chrome.jpg…]()

**Comment by marwan** [comment]
Seems like there is a cropping issue even for digital hafs font on the left side of the page. Need to check and fix. 

![IMG_20240606_105900.jpg](https://github.com/marwan/quranwbw-v4/assets/8071158/667f60e4-fcc9-49fa-b74f-8858347229f2)
