### ISSUE TITLE
Quiz - display tick mark on correct answer when user enters any answer.

### ISSUE THREAD

**Issue by Ayman24x7** [marwan/quranwbw-v4#94]

**Comment by marwan** [comment]
this was completed in https://github.com/marwan/quranwbw-v4/commit/43843ccca1d2df4cc1dbbcc6b20b8b9bd149e499

![image](https://github.com/marwan/quranwbw-v4/assets/8071158/b997692b-df5f-44b5-a4ed-547e70e47a7d)
